export const DUMMY_STAYS = [
  { id: 'd1', slug: 'tentrem-hotel', name_id: 'Hotel Tentrem', name_en: 'Tentrem Hotel', regency: 'kota-yogyakarta', price_idr_per_night: 1500000, star_rating: 5, hero_image_url: 'https://images.unsplash.com/photo-1566073771259-6a8506099945?w=1200&q=80', gallery_image_urls: ['https://images.unsplash.com/photo-1611892440504-42a792e24d32?w=1200&q=80', 'https://images.unsplash.com/photo-1590490360182-c33d57733427?w=1200&q=80'], amenities: ['Pool', 'Spa', 'Gym', 'Restaurant', 'Free Wi-Fi', 'Airport shuttle'], address: 'Jl. AM Sangaji No. 72A, Kota Yogyakarta', check_in_time: '14:00', check_out_time: '12:00', description_en: '<p>Hotel Tentrem is a five-star landmark on the northern edge of central Yogyakarta, purpose-built to feel like a Javanese royal residence rather than a chain hotel. Expect polished teak, hand-woven textiles, and staff trained in the courtly hospitality Jogja is quietly famous for.</p><p>The property is a short drive from Malioboro and the Kraton, yet feels tucked away — a rare balance for a city hotel. Suites are unusually large by Indonesian standards, the spa is genuinely world-class, and breakfast alone is worth the stay.</p>', description_id: '<p>Hotel Tentrem adalah landmark bintang lima di sisi utara pusat Yogyakarta, dibangun agar terasa seperti kediaman bangsawan Jawa alih-alih hotel berjaringan. Interior kayu jati, tenunan tangan, dan pelayanan bergaya keraton menjadi ciri khasnya.</p><p>Jaraknya dekat dari Malioboro dan Keraton, namun tetap terasa tenang — kombinasi yang jarang di hotel pusat kota. Kamar-kamar suite berukuran besar, spa-nya kelas dunia, dan sarapan paginya saja sudah cukup jadi alasan menginap.</p>' },
  { id: 'd2', slug: 'hyatt-regency', name_id: 'Hyatt Regency Yogyakarta', name_en: 'Hyatt Regency Yogyakarta', regency: 'sleman', price_idr_per_night: 1200000, star_rating: 5, hero_image_url: 'https://images.unsplash.com/photo-1542314831-c6a4d1424b36?w=1200&q=80', amenities: ['Golf course', 'Pool', 'Spa', 'Restaurant', 'Free Wi-Fi'], address: 'Jl. Palagan Tentara Pelajar, Sleman', check_in_time: '15:00', check_out_time: '12:00', description_en: '<p>Set on 22 hectares north of the city, Hyatt Regency Yogyakarta is more resort than hotel — with its own nine-hole golf course, three pools, and views of Mount Merapi on clear mornings.</p><p>Ideal for travellers who want space to breathe after temple-hopping and prefer their evenings quiet. The city centre is a 25-minute drive; the airport transfer desk handles the rest.</p>', description_id: '<p>Berlokasi di lahan 22 hektare di utara kota, Hyatt Regency Yogyakarta lebih terasa seperti resort — lengkap dengan lapangan golf sembilan hole, tiga kolam renang, dan pemandangan Gunung Merapi di pagi yang cerah.</p><p>Cocok untuk pelancong yang butuh ruang setelah seharian menjelajah candi. Pusat kota berjarak 25 menit; transfer bandara mudah diatur di lobi.</p>' },
  { id: 'd3', slug: 'amanjiwo', name_id: 'Amanjiwo Resort', name_en: 'Amanjiwo Resort', regency: 'sleman', price_idr_per_night: 8000000, star_rating: 5, hero_image_url: 'https://images.unsplash.com/photo-1582719478250-c89cae4dc85b?w=1200&q=80', amenities: ['Pool', 'Spa', 'Private terrace', 'Restaurant', 'Butler service'], address: 'Ds. Majaksingi, Borobudur, Magelang', check_in_time: '14:00', check_out_time: '12:00', description_en: '<p>Amanjiwo sits in a natural amphitheatre facing Borobudur, its stone rotunda echoing the temple silhouette on the horizon. It is widely considered one of the finest resorts in Asia, and the price reflects it.</p><p>The 36 free-standing suites each open onto a private terrace with volcano views. Sunrise breakfasts at the temple, gamelan performances at dusk, and a spa built into a valley set the standard other resorts try to reach.</p>', description_id: '<p>Amanjiwo terletak di amfiteater alami menghadap Borobudur, dengan bangunan rotunda batu yang menggemakan siluet candi di kejauhan. Kerap disebut salah satu resort terbaik di Asia — dan harganya memang sepadan.</p><p>Ke-36 suite berdiri sendiri, masing-masing dengan teras pribadi menghadap gunung berapi. Sarapan sunrise di candi, pertunjukan gamelan sore hari, dan spa yang menyatu dengan lembah — semuanya menjadi standar yang dikejar resort lain.</p>' },
  { id: 'd4', slug: 'greenhost', name_id: 'Greenhost Boutique Hotel', name_en: 'Greenhost Boutique Hotel', regency: 'kota-yogyakarta', price_idr_per_night: 600000, star_rating: 4, hero_image_url: 'https://images.unsplash.com/photo-1574686419519-74d11cb1e976?w=1200&q=80', amenities: ['Rooftop garden', 'Art gallery', 'Cafe', 'Free Wi-Fi', 'Bicycle rental'], address: 'Jl. Prawirotaman II No. 629, Kota Yogyakarta', check_in_time: '14:00', check_out_time: '12:00', description_en: '<p>Greenhost is Prawirotaman\'s most beloved boutique hotel — an urban-farm-meets-art-gallery concept that draws creatives, remote workers, and design-minded travellers.</p><p>Rooms are simple and calm; the real character is in the shared spaces: the aquaponic rooftop garden, the ground-floor cafe, and rotating exhibitions by Jogja artists. Walking distance to warungs, coffee shops, and batik studios.</p>', description_id: '<p>Greenhost adalah hotel butik favorit di Prawirotaman — konsep urban farm dan galeri seni yang menarik para kreatif, digital nomad, dan pelancong berjiwa desain.</p><p>Kamarnya sederhana dan tenang; karakternya justru terasa di ruang bersama: kebun aquaponic di atap, kafe di lantai dasar, dan pameran seniman Jogja yang berganti-ganti. Warung, kedai kopi, dan studio batik semuanya dalam jarak berjalan kaki.</p>' }
];

export const DUMMY_EVENTS = [
  { id: 'd1', slug: 'prambanan-jazz', name_id: 'Prambanan Jazz Festival', name_en: 'Prambanan Jazz Festival', event_date: '2027-07-10', regency: 'sleman', event_type: 'Music', hero_image_url: 'https://images.unsplash.com/photo-1540039155732-61ee01ba2986?w=600&q=80', category: 'music' },
  { id: 'd2', slug: 'sekaten', name_id: 'Pasar Malam Sekaten', name_en: 'Sekaten Night Market', event_date: '2027-09-01', regency: 'kota-yogyakarta', event_type: 'Festival', hero_image_url: 'https://images.unsplash.com/photo-1533174000255-598d38f1a4bb?w=600&q=80', category: 'festival' },
  { id: 'd3', slug: 'ramayana', name_id: 'Sendratari Ramayana', name_en: 'Ramayana Ballet', event_date: '2027-08-15', regency: 'sleman', event_type: 'Cultural', hero_image_url: 'https://images.unsplash.com/photo-1596402184320-417e7178b2cd?w=600&q=80', category: 'cultural' },
  { id: 'd4', slug: 'artjog', name_id: 'ArtJog', name_en: 'ArtJog', event_date: '2027-06-20', regency: 'kota-yogyakarta', event_type: 'Art Exhibition', hero_image_url: 'https://images.unsplash.com/photo-1513364776144-60967b0f800f?w=600&q=80', category: 'exhibition' },
  { id: 'd5', slug: 'jogja-marathon', name_id: 'Marathon Jogja', name_en: 'Jogja Marathon', event_date: '2027-10-15', regency: 'kota-yogyakarta', event_type: 'Sports', hero_image_url: 'https://images.unsplash.com/photo-1452626038306-9aae5e071dd3?w=600&q=80', category: 'sports' }
];

export const DUMMY_ITINERARIES = [
  { id: 'd1', slug: '3-days-heritage', title_id: '3 Hari Menyusuri Warisan Jogja', title_en: '3 Days Jogja Heritage Trail', summary_id: 'Jelajahi candi-candi megah dan budaya lokal dalam waktu singkat.', summary_en: 'Explore majestic temples and local culture in a short time.', duration_days: 3, cover_image_url: 'https://images.unsplash.com/photo-1584810359583-96fc9f6bffb0?w=600&q=80' },
  { id: 'd2', slug: '5-days-nature', title_id: '5 Hari Petualangan Alam', title_en: '5 Days Nature Adventure', summary_id: 'Nikmati keindahan pantai selatan dan pegunungan utara.', summary_en: 'Enjoy the beauty of southern beaches and northern mountains.', duration_days: 5, cover_image_url: 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=600&q=80' },
  { id: 'd3', slug: 'weekend-getaway', title_id: 'Liburan Akhir Pekan', title_en: 'Weekend Getaway', summary_id: 'Rencana santai untuk menikmati kuliner dan belanja di kota.', summary_en: 'A relaxing plan to enjoy culinary and shopping in the city.', duration_days: 2, cover_image_url: 'https://images.unsplash.com/photo-1512100356356-de1b84283e18?w=600&q=80' }
];

export const DUMMY_DESTINATIONS = [
  { id: 'd1', slug: 'borobudur', name_id: 'Candi Borobudur', name_en: 'Borobudur Temple', category: 'heritage-culture', regency: 'sleman', experience_type: ['heritage-culture'], hero_image_url: 'https://images.unsplash.com/photo-1508009603885-50cf7c579365?w=600&q=80', excerpt_id: 'Candi Buddha terbesar di dunia.', excerpt_en: 'The largest Buddhist temple in the world.' },
  { id: 'd2', slug: 'malioboro', name_id: 'Jalan Malioboro', name_en: 'Malioboro Street', category: 'entertainment-creative', regency: 'kota-yogyakarta', experience_type: ['entertainment-creative', 'culinary-lifestyle'], hero_image_url: 'https://images.unsplash.com/photo-1596402184320-417e7178b2cd?w=600&q=80', excerpt_id: 'Pusat belanja dan budaya kota.', excerpt_en: 'The city shopping and cultural center.' },
  { id: 'd3', slug: 'parangtritis', name_id: 'Pantai Parangtritis', name_en: 'Parangtritis Beach', category: 'sports-adventure', regency: 'bantul', experience_type: ['sports-adventure'], hero_image_url: 'https://images.unsplash.com/photo-1544551763-46a013bb70d5?w=600&q=80', excerpt_id: 'Pantai ikonik di selatan Jogja.', excerpt_en: 'Iconic beach in southern Jogja.' },
  { id: 'd4', slug: 'goa-pindul', name_id: 'Goa Pindul', name_en: 'Pindul Cave', category: 'sports-adventure', regency: 'gunungkidul', experience_type: ['sports-adventure'], hero_image_url: 'https://images.unsplash.com/photo-1523712999610-f77fbcfc3843?w=600&q=80', excerpt_id: 'Petualangan cave tubing seru.', excerpt_en: 'Exciting cave tubing adventure.' }
];

export const DUMMY_DISCOVER = {
  hero_image_url: 'https://images.unsplash.com/photo-1626018944638-6bebc0e0f8a5?w=1200&q=80',
  title_id: 'Mengenal Jogja Lebih Dalam',
  title_en: 'Getting to Know Jogja',
  body_id: '<p>Yogyakarta, atau sering disebut Jogja, merupakan pusat seni dan budaya klasik Jawa. Kota ini menawarkan perpaduan unik antara tradisi kuno yang masih lestari dan denyut kehidupan modern yang dinamis.</p><p>Dari kemegahan keraton hingga keramahan penduduknya, setiap sudut Jogja memiliki cerita untuk dibagikan.</p>',
  body_en: '<p>Yogyakarta, often called Jogja, is the center of classical Javanese art and culture. The city offers a unique blend of ancient traditions that are still alive and a dynamic modern pulse.</p><p>From the grandeur of the palace to the hospitality of its people, every corner of Jogja has a story to share.</p>'
};

export const DUMMY_TOURS = [
  { id: 'd1', slug: 'merapi-lavatour', name_id: 'Tur Lava Merapi', name_en: 'Merapi Lava Tour', regency: 'sleman', price_idr: 350000, duration_hours: 3, hero_image_url: 'https://images.unsplash.com/photo-1519681393784-d120267933ba?w=1200&q=80', gallery_image_urls: ['https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?w=1200&q=80', 'https://images.unsplash.com/photo-1508881598464-c78141aefda2?w=1200&q=80', 'https://images.unsplash.com/photo-1502786129293-79981df4e689?w=1200&q=80', 'https://images.unsplash.com/photo-1476514525535-07fb3b4ae5f1?w=1200&q=80'], descriptor_id: 'Menyusuri lereng Gunung Merapi dengan jeep 4x4 legendaris, melewati bekas aliran lava dari erupsi 2010 yang mengubah wajah desa-desa di kaki gunung. Tur ini bukan sekadar tur alam — ini kesempatan mendengar langsung cerita para penyintas, menyentuh sisa-sisa material vulkanik, dan memahami hubungan orang Jawa dengan gunung yang mereka anggap suci.', descriptor_en: 'Ride a classic 4x4 jeep across the slopes of Mount Merapi, tracing the lava paths of the 2010 eruption that reshaped the villages at the mountain\'s foot. This is more than a landscape tour — it is a chance to hear survivors\' stories firsthand, touch volcanic remnants, and understand the deep bond Javanese communities share with a mountain they consider sacred.', highlights: ['Bunker Kaliadem', 'Museum Sisa Hartaku', 'Batu Alien', 'Off-road jeep experience'], meeting_point_en: 'Kaliurang jeep base, Sleman', meeting_point_id: 'Base jeep Kaliurang, Sleman' },
  { id: 'd2', slug: 'heritage-cycling', name_id: 'Bersepeda Menyusuri Desa', name_en: 'Heritage Village Cycling', regency: 'bantul', price_idr: 150000, duration_hours: 4, hero_image_url: 'https://images.unsplash.com/photo-1512100356356-de1b84283e18?w=1200&q=80', gallery_image_urls: ['https://images.unsplash.com/photo-1517649763962-0c623066013b?w=1200&q=80', 'https://images.unsplash.com/photo-1471506480208-91b3a4cc78be?w=1200&q=80', 'https://images.unsplash.com/photo-1518709268805-4e9042af9f23?w=1200&q=80'], descriptor_id: 'Tur sepeda santai yang membawa kamu keluar dari hiruk-pikuk kota dan masuk ke desa-desa tradisional di Bantul. Berhenti di rumah pengrajin gerabah, sawah yang masih dikelola manual, dan warung kecil untuk mencicipi kopi lokal. Cocok untuk kamu yang ingin merasakan denyut Jogja di luar tempat wisata utama.', descriptor_en: 'A relaxed cycling tour that pulls you out of the city noise and into the traditional villages of Bantul. Stop at potters\' homes, rice paddies still worked by hand, and roadside warungs for a taste of local coffee. Best for travellers who want to feel Jogja\'s pulse away from the main tourist trail.', highlights: ['Village potter visit', 'Rice paddy trails', 'Local coffee stop', 'Small-group friendly'], meeting_point_en: 'Kasongan Pottery Village, Bantul', meeting_point_id: 'Desa Gerabah Kasongan, Bantul' },
  { id: 'd3', slug: 'prambanan-sunset', name_id: 'Tur Matahari Terbenam Prambanan', name_en: 'Prambanan Sunset Tour', regency: 'sleman', price_idr: 450000, duration_hours: 5, hero_image_url: 'https://images.unsplash.com/photo-1596402184320-417e7178b2cd?w=1200&q=80', gallery_image_urls: ['https://images.unsplash.com/photo-1553913861-c0fddf2619ee?w=1200&q=80', 'https://images.unsplash.com/photo-1584810359583-96fc9f6bffb0?w=1200&q=80', 'https://images.unsplash.com/photo-1552733407-5d5c46c3bb3b?w=1200&q=80'], descriptor_id: 'Nikmati kompleks candi Hindu terbesar di Indonesia dalam cahaya yang paling dramatis — saat matahari perlahan turun di balik siluet tiga menara utama. Tur ini mencakup pemandu berlisensi, penjelasan bas-relief Ramayana, dan diakhiri dengan pertunjukan sendratari klasik (opsional).', descriptor_en: 'Experience Indonesia\'s largest Hindu temple compound in its most dramatic light — as the sun sinks behind the silhouette of the three main spires. Includes a licensed guide, an in-depth reading of the Ramayana bas-reliefs, and an optional evening ballet performance to close the day.', highlights: ['Licensed local guide', 'Golden-hour photography', 'Ramayana bas-relief walk', 'Optional dance performance'], meeting_point_en: 'Prambanan Temple main gate', meeting_point_id: 'Gerbang utama Candi Prambanan' },
  { id: 'd4', slug: 'food-tour', name_id: 'Tur Kuliner Malam', name_en: 'Night Food Tour', regency: 'kota-yogyakarta', price_idr: 250000, duration_hours: 3, hero_image_url: 'https://images.unsplash.com/photo-1513364776144-60967b0f800f?w=1200&q=80', gallery_image_urls: ['https://images.unsplash.com/photo-1555396273-367ea4eb4db5?w=1200&q=80', 'https://images.unsplash.com/photo-1504674900247-0877df9cc836?w=1200&q=80', 'https://images.unsplash.com/photo-1467003909585-2f8a72700288?w=1200&q=80'], descriptor_id: 'Jogja terkenal dengan kuliner malamnya, dan tur ini adalah cara terbaik memahaminya — bukan sekadar mencicipi, tapi mendengar cerita di balik setiap warung. Dari gudeg legendaris hingga angkringan pinggir jalan, kamu akan makan sebanyak enam tempat berbeda ditemani pemandu lokal.', descriptor_en: 'Jogja is famous for its night food scene, and this tour is the smartest way to make sense of it — not just tasting, but hearing the story behind every stall. From legendary gudeg houses to trackside angkringan, you\'ll eat your way through six stops with a local guide who knows the family behind each.', highlights: ['6 hand-picked stops', 'Local guide throughout', 'All food included', 'Vegetarian option available'], meeting_point_en: 'Malioboro Street tourist information post', meeting_point_id: 'Pos informasi wisata Jalan Malioboro' }
];

export const DUMMY_VISITOR_INFO = [
  {
    id: 'v1', slug: 'getting-to-jogja', icon_name: 'Plane', display_order: 1,
    title_en: 'Getting to Jogja', title_id: 'Menuju ke Jogja',
    desc_en: 'Information on airports, train stations, and bus terminals.',
    desc_id: 'Informasi tentang bandara, stasiun kereta, dan terminal bus.',
    image_url: 'https://images.unsplash.com/photo-rIW0doyBrK0?w=600&q=80',
    items: [
      {
        title_en: 'Airports', title_id: 'Bandara',
        desc_en: 'Yogyakarta International Airport (YIA) serves both domestic and international flights with modern facilities.',
        desc_id: 'Bandara Internasional Yogyakarta (YIA) melayani penerbangan domestik dan internasional dengan fasilitas modern.',
        image_url: 'https://images.unsplash.com/photo-1436491865332-7a61a109cc05?w=600&q=80'
      },
      {
        title_en: 'Train Stations', title_id: 'Stasiun Kereta',
        desc_en: 'Tugu Station is the main railway hub for executive trains, located right in the city center.',
        desc_id: 'Stasiun Tugu adalah pusat kereta api utama untuk kelas eksekutif, terletak tepat di pusat kota.',
        image_url: 'https://images.unsplash.com/photo-1474487548417-781cb71495f3?w=600&q=80'
      },
      {
        title_en: 'Bus Terminals', title_id: 'Terminal Bus',
        desc_en: 'Giwangan is the primary intercity bus terminal connecting Jogja to various regions in Java.',
        desc_id: 'Giwangan adalah terminal bus antarkota utama yang menghubungkan Jogja ke berbagai wilayah di Jawa.',
        image_url: 'https://images.unsplash.com/photo-1544620347-c4fd4a3d5957?w=600&q=80'
      },
      {
        title_en: 'Intercity Transportation', title_id: 'Transportasi Antar Kota',
        desc_en: 'Minibuses and private shuttles offer convenient point-to-point connections to neighboring cities.',
        desc_id: 'Minibus dan travel pribadi menawarkan koneksi dari titik ke titik yang nyaman ke kota-kota tetangga.',
        image_url: 'https://images.unsplash.com/photo-1638210342930-1b777a82c40c?w=600&q=80'
      }
    ]
  },
  {
    id: 'v2', slug: 'transport', icon_name: 'Bus', display_order: 2,
    title_en: 'Getting Around', title_id: 'Transportasi Lokal',
    desc_en: 'Navigate Yogyakarta with ease using various local transport options.',
    desc_id: 'Jelajahi Yogyakarta dengan mudah menggunakan berbagai pilihan transportasi lokal.',
    image_url: 'https://images.unsplash.com/photo-c5dXzwnPkOk?w=600&q=80',
    items: [
      { title_en: 'Taxi', title_id: 'Taksi', desc_en: 'Metered taxis are widely available across the city.', desc_id: 'Taksi argo tersedia secara luas di seluruh kota.', image_url: 'https://images.unsplash.com/photo-1549317661-bd32c8ce0db2?w=600&q=80' },
      { title_en: 'Online Transportation', title_id: 'Transportasi Online', desc_en: 'Ride-hailing apps like Gojek and Grab are very popular and affordable.', desc_id: 'Aplikasi transportasi seperti Gojek dan Grab sangat populer dan terjangkau.', image_url: 'https://images.unsplash.com/photo-1621538355029-768132ce0d96?w=600&q=80' },
      { title_en: 'Trans Jogja', title_id: 'Trans Jogja', desc_en: 'An affordable BRT system that covers major tourist spots.', desc_id: 'Sistem BRT terjangkau yang menjangkau tempat wisata utama.', image_url: 'https://images.unsplash.com/photo-1520627581566-51e44f808fcb?w=600&q=80' },
      { title_en: 'Car Rental', title_id: 'Sewa Mobil', desc_en: 'Rent a car with or without a driver for flexible exploration.', desc_id: 'Sewa mobil dengan atau tanpa sopir untuk penjelajahan yang fleksibel.', image_url: 'https://images.unsplash.com/photo-1449965408869-eaa3f722e40d?w=600&q=80' }
    ]
  },
  {
    id: 'v3', slug: 'health-emergency', icon_name: 'HeartPulse', display_order: 3,
    title_en: 'Health & Emergency', title_id: 'Kesehatan & Darurat',
    desc_en: 'Important information regarding healthcare facilities and emergency contacts.',
    desc_id: 'Informasi penting mengenai fasilitas kesehatan dan kontak darurat.',
    image_url: 'https://images.unsplash.com/photo-msyQNw7AfJ0?w=600&q=80',
    items: [
      { title_en: 'Hospitals', title_id: 'Rumah Sakit', desc_en: 'International standard hospitals available 24/7 for emergencies.', desc_id: 'Rumah sakit standar internasional tersedia 24/7 untuk keadaan darurat.', image_url: 'https://images.unsplash.com/photo-1519494026892-80bbd2d6fd0d?w=600&q=80' },
      { title_en: 'Pharmacies', title_id: 'Apotek', desc_en: 'Many pharmacies (Apotek) operate late or 24 hours around the city center.', desc_id: 'Banyak apotek beroperasi larut malam atau 24 jam di sekitar pusat kota.', image_url: 'https://images.unsplash.com/photo-1587854692152-cbe660dbde88?w=600&q=80' },
      { title_en: 'Police Stations', title_id: 'Kantor Polisi', desc_en: 'Tourist police are helpful for reporting lost items or incidents.', desc_id: 'Polisi pariwisata sangat membantu untuk melaporkan barang hilang atau insiden.', image_url: 'https://images.unsplash.com/photo-1598463943360-6435c2b0c1ec?w=600&q=80' },
      { title_en: 'Emergency Numbers', title_id: 'Nomor Darurat', desc_en: 'Dial 112 for general emergencies, 118 for ambulance, 110 for police.', desc_id: 'Hubungi 112 untuk keadaan darurat umum, 118 untuk ambulans, 110 untuk polisi.', image_url: 'https://images.unsplash.com/photo-1534081333815-ae5019106622?w=600&q=80' }
    ]
  },
  {
    id: 'v4', slug: 'money-communication', icon_name: 'Banknote', display_order: 4,
    title_en: 'Money & Communication', title_id: 'Uang & Komunikasi',
    desc_en: 'Practical tips on money changers, ATMs, and internet access.',
    desc_id: 'Tips praktis tentang penukaran uang, ATM, dan akses internet.',
    image_url: 'https://images.unsplash.com/photo-UGg0AODkGJs?w=600&q=80',
    items: [
      { title_en: 'Money Changers', title_id: 'Penukaran Uang', desc_en: 'Authorized money changers offer competitive rates without hidden fees.', desc_id: 'Tempat penukaran uang resmi menawarkan nilai tukar kompetitif tanpa biaya tersembunyi.', image_url: 'https://images.unsplash.com/photo-1580519542036-ed47f3e404b9?w=600&q=80' },
      { title_en: 'Banks and ATMs', title_id: 'Bank dan ATM', desc_en: 'ATMs are everywhere. Most accept major international cards.', desc_id: 'ATM ada di mana-mana. Sebagian besar menerima kartu internasional.', image_url: 'https://images.unsplash.com/photo-1620714223084-8fcacc6dfd8d?w=600&q=80' },
      { title_en: 'SIM Cards', title_id: 'Kartu SIM', desc_en: 'Prepaid SIM cards for data can be easily purchased at phone kiosks.', desc_id: 'Kartu SIM prabayar untuk data dapat dengan mudah dibeli di kios ponsel.', image_url: 'https://images.unsplash.com/photo-1592890288564-76628a30a657?w=600&q=80' },
      { title_en: 'Internet and Wi-Fi', title_id: 'Internet dan Wi-Fi', desc_en: 'Free Wi-Fi is common in cafes, hotels, and some public spaces.', desc_id: 'Wi-Fi gratis umum ditemukan di kafe, hotel, dan beberapa ruang publik.', image_url: 'https://images.unsplash.com/photo-1563207153-f403bf289096?w=600&q=80' }
    ]
  },
  {
    id: 'v5', slug: 'wellness-fitness', icon_name: 'Activity', display_order: 5,
    title_en: 'Wellness & Fitness', title_id: 'Kebugaran & Kesejahteraan',
    desc_en: 'Facilities and places for wellness, spa, and fitness activities.',
    desc_id: 'Fasilitas dan tempat untuk aktivitas kebugaran, spa, dan kesehatan.',
    image_url: 'https://demo.experiencejogja.com/images/visitor-info/wellness-and-health-IMG-00030-w2000.jpg',
    items: [
      { title_en: 'Spas', title_id: 'Spa', desc_en: 'Indulge in traditional Javanese massage and spa treatments.', desc_id: 'Manjakan diri dengan pijat tradisional Jawa dan perawatan spa.', image_url: 'https://images.unsplash.com/photo-1544161515-4ab6ce6db874?w=600&q=80' },
      { title_en: 'Gyms', title_id: 'Gym', desc_en: 'Modern fitness centers are available in major hotels and malls.', desc_id: 'Pusat kebugaran modern tersedia di hotel-hotel besar dan mal.', image_url: 'https://images.unsplash.com/photo-1534438327276-14e5300c3a48?w=600&q=80' },
      { title_en: 'Yoga', title_id: 'Yoga', desc_en: 'Join yoga retreats and daily classes scattered around cultural hubs.', desc_id: 'Ikuti retret yoga dan kelas harian yang tersebar di pusat budaya.', image_url: 'https://images.unsplash.com/photo-1544367567-0f2fcb009e0b?w=600&q=80' },
      { title_en: 'Swimming Pools', title_id: 'Kolam Renang', desc_en: 'Public and hotel pools offer a great way to cool down.', desc_id: 'Kolam renang umum dan hotel menawarkan cara yang bagus untuk menyegarkan diri.', image_url: 'https://images.unsplash.com/photo-1519682577862-22b62b24e493?w=600&q=80' }
    ]
  },
  {
    id: 'v6', slug: 'public-facilities', icon_name: 'Wifi', display_order: 6,
    title_en: 'Public Facilities', title_id: 'Fasilitas Umum',
    desc_en: 'Access public toilets, information centers, and other essential facilities.',
    desc_id: 'Akses toilet umum, pusat informasi, dan fasilitas penting lainnya.',
    image_url: 'https://images.unsplash.com/photo-8yDJZ92_H9Y?w=600&q=80',
    items: [
      { title_en: 'Information Centers', title_id: 'Pusat Informasi', desc_en: 'Tourist information centers are located in Malioboro and airports.', desc_id: 'Pusat informasi turis berlokasi di Malioboro dan bandara.', image_url: 'https://images.unsplash.com/photo-1531206715517-5c0ba140b2b8?w=600&q=80' },
      { title_en: 'Prayer Facilities', title_id: 'Fasilitas Ibadah', desc_en: 'Musholas (prayer rooms) are easily found in all public areas and malls.', desc_id: 'Mushola mudah ditemukan di seluruh area publik dan mal.', image_url: 'https://images.unsplash.com/photo-1564287827878-a006db231f4e?w=600&q=80' },
      { title_en: 'Public Toilets', title_id: 'Toilet Umum', desc_en: 'Maintained public toilets are available in tourist districts for a small fee.', desc_id: 'Toilet umum yang terawat tersedia di kawasan wisata dengan biaya kecil.', image_url: 'https://images.unsplash.com/photo-1584622650111-993a426fbf0a?w=600&q=80' },
      { title_en: 'Luggage Storage', title_id: 'Penitipan Barang', desc_en: 'Available at Tugu Station for travelers wanting to explore hands-free.', desc_id: 'Tersedia di Stasiun Tugu untuk wisatawan yang ingin menjelajah tanpa beban.', image_url: 'https://images.unsplash.com/photo-1555353133-c2890529d2f2?w=600&q=80' }
    ]
  }
];

export const DUMMY_ATTRACTIONS = [
  { id: 'a1', slug: 'borobudur-sunrise', name_en: 'Borobudur Sunrise Tour', name_id: 'Tur Sunrise Borobudur', category: 'heritage', regency: 'sleman', price_idr: 450000, hero_image_url: 'https://images.unsplash.com/photo-1596402184320-417e7178b2cd?w=600&q=80', descriptor_en: 'Experience the magical sunrise over the world\'s largest Buddhist temple.' },
  { id: 'a2', slug: 'timang-beach-gondola', name_en: 'Timang Beach Gondola', name_id: 'Gondola Pantai Timang', category: 'adventure', regency: 'gunungkidul', price_idr: 100000, hero_image_url: 'https://images.unsplash.com/photo-1544551763-46a013bb70d5?w=600&q=80', descriptor_en: 'Ride the thrilling traditional gondola across the ocean waves.' },
  { id: 'a3', slug: 'prambanan-temple', name_en: 'Prambanan Temple Complex', name_id: 'Kompleks Candi Prambanan', category: 'heritage', regency: 'sleman', price_idr: 350000, hero_image_url: 'https://images.unsplash.com/photo-1584810359583-96fc9f6bffb0?w=600&q=80', descriptor_en: 'Explore the largest Hindu temple compound in Indonesia.' },
];

export const DUMMY_ACTIVITIES = [
  { id: 'ac1', slug: 'batik-workshop', name_en: 'Batik Making Workshop', name_id: 'Workshop Membatik', category: 'culture', duration_hours: 3, price_idr: 200000, regency: 'kota-yogyakarta', hero_image_url: 'https://images.unsplash.com/photo-1513364776144-60967b0f800f?w=1200&q=80', gallery_image_urls: ['https://images.unsplash.com/photo-1528459801416-a9e53bbf4e17?w=1200&q=80', 'https://images.unsplash.com/photo-1489533119213-66a5cd877091?w=1200&q=80', 'https://images.unsplash.com/photo-1490645935967-10de6ba17061?w=1200&q=80'], descriptor_en: 'Batik is not just a fabric — it is a language. In this hands-on workshop, a master artisan will teach you the canting wax-resist technique that has been passed down for generations. You will leave with your own hand-drawn piece and a much deeper appreciation for the cloths hanging in every Jogja boutique.', descriptor_id: 'Batik bukan sekadar kain — batik adalah bahasa. Dalam workshop langsung ini, pengrajin senior akan mengajarkan teknik canting yang diwariskan lintas generasi. Kamu akan pulang membawa karya buatan sendiri, dan pemahaman baru tentang kain yang menggantung di setiap butik Jogja.', highlights: ['Guided by master artisan', 'All materials included', 'Take your batik home', 'Small class size'], meeting_point_en: 'Batik Winotosastro workshop, Tirtodipuran', meeting_point_id: 'Workshop Batik Winotosastro, Tirtodipuran' },
  { id: 'ac2', slug: 'cave-tubing-pindul', name_en: 'Cave Tubing at Goa Pindul', name_id: 'Cave Tubing Goa Pindul', category: 'adventure', duration_hours: 2, price_idr: 75000, regency: 'gunungkidul', hero_image_url: 'https://images.unsplash.com/photo-1523712999610-f77fbcfc3843?w=1200&q=80', gallery_image_urls: ['https://images.unsplash.com/photo-1502786129293-79981df4e689?w=1200&q=80', 'https://images.unsplash.com/photo-1444492417251-9c84a5fa18e0?w=1200&q=80'], descriptor_en: 'Float through a limestone cave on an inner tube, following an underground river carved over millennia. The light drops away, stalactites hang low overhead, and for 45 quiet minutes you drift through one of the most surreal landscapes in Java. Family-friendly and safe for non-swimmers with a life vest.', descriptor_id: 'Mengapung menyusuri gua kapur di atas ban dalam, mengikuti sungai bawah tanah yang terbentuk ribuan tahun. Cahaya perlahan menghilang, stalaktit menggantung rendah, dan selama 45 menit kamu meluncur di lanskap paling surealis di Jawa. Aman untuk keluarga dan yang tidak bisa berenang (dengan life vest).', highlights: ['Life vest & tube provided', 'Local guide', 'Family friendly', 'Photos included'], meeting_point_en: 'Goa Pindul Secretariat, Bejiharjo, Gunungkidul', meeting_point_id: 'Sekretariat Goa Pindul, Bejiharjo, Gunungkidul' },
  { id: 'ac3', slug: 'silver-jewelry-class', name_en: 'Silver Jewelry Making Class', name_id: 'Kelas Membuat Perhiasan Perak', category: 'culture', duration_hours: 4, price_idr: 300000, regency: 'bantul', hero_image_url: 'https://images.unsplash.com/photo-1515377905703-c4788e51af15?w=1200&q=80', gallery_image_urls: ['https://images.unsplash.com/photo-1611652022419-a9419f74343d?w=1200&q=80', 'https://images.unsplash.com/photo-1611591437281-460bfbe1220a?w=1200&q=80'], descriptor_en: 'Kotagede has been Jogja\'s silver quarter for over 400 years, back to the days of the Mataram Sultanate. In this class you will spend an afternoon in a working atelier — hammering, soldering, and polishing a piece of your own design under the eye of a third-generation silversmith.', descriptor_id: 'Kotagede telah menjadi kampung perak Jogja selama lebih dari 400 tahun, sejak masa Kesultanan Mataram. Di kelas ini kamu akan menghabiskan sore di studio yang masih aktif — memukul, menyolder, dan memoles karya rancanganmu sendiri, dibimbing pengrajin generasi ketiga.', highlights: ['Working Kotagede atelier', 'Take home your creation', '3rd-generation silversmith', 'All tools provided'], meeting_point_en: 'HS Silver workshop, Kotagede', meeting_point_id: 'Workshop HS Silver, Kotagede' },
];

export const DUMMY_RESTAURANTS = [
  { id: 'r1', slug: 'bale-raos', name_en: 'Bale Raos Royal Cuisine', name_id: 'Bale Raos Masakan Keraton', cuisine: 'javanese', price_range: '$$', regency: 'kota-yogyakarta', hero_image_url: 'https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?w=1200&q=80', gallery_image_urls: ['https://images.unsplash.com/photo-1555396273-367ea4eb4db5?w=1200&q=80', 'https://images.unsplash.com/photo-1550966871-3ed3cdb5ed0c?w=1200&q=80', 'https://images.unsplash.com/photo-1590846406792-0adc7f938f1d?w=1200&q=80'], descriptor_en: 'Bale Raos sits inside the Kraton walls and serves the actual recipes cooked for the Sultan\'s family — dishes rarely available anywhere else in Indonesia. Order the bebek suwar-suwir or manuk nom to taste what royal Javanese cuisine actually means, plated in a garden pavilion under century-old teak beams.', descriptor_id: 'Bale Raos berada di dalam kompleks Keraton dan menyajikan resep-resep yang dulunya khusus dimasak untuk keluarga Sultan — hidangan yang hampir tak ditemukan di tempat lain. Pesan bebek suwar-suwir atau manuk nom untuk mencicipi masakan bangsawan Jawa yang sesungguhnya, di pavilion taman dengan balok jati berusia seabad.', highlights: ['Inside the Kraton compound', 'Authentic royal recipes', 'Open-air pavilion dining', 'Reservations recommended'], address: 'Jl. Magangan Kulon No. 1, Kraton, Yogyakarta', opening_hours: '11:00 – 22:00' },
  { id: 'r2', slug: 'mediterranea', name_en: 'Mediterranea Restaurant', name_id: 'Restoran Mediterranea', cuisine: 'international', price_range: '$$$', regency: 'sleman', hero_image_url: 'https://images.unsplash.com/photo-1414235077428-338989a2e8c0?w=1200&q=80', gallery_image_urls: ['https://images.unsplash.com/photo-1466978913421-dad2ebd01d17?w=1200&q=80', 'https://images.unsplash.com/photo-1544025162-d76694265947?w=1200&q=80', 'https://images.unsplash.com/photo-1600891964092-4316c288032e?w=1200&q=80'], descriptor_en: 'One of Jogja\'s longest-running fine-dining rooms, Mediterranea is set in a lush walled garden north of the city. The wine list is unusually deep for Indonesia, the pasta is made in-house daily, and the wood-fired pizza is the sort you dream about between visits. Perfect for a slower, celebratory evening.', descriptor_id: 'Salah satu restoran fine-dining paling lama bertahan di Jogja, Mediterranea berada di taman berpagar rimbun di utara kota. Daftar wine-nya tidak biasa untuk ukuran Indonesia, pasta dibuat harian, dan pizza wood-fired-nya termasuk yang paling dirindukan. Cocok untuk malam istimewa yang lebih santai.', highlights: ['Deep wine list', 'Fresh house-made pasta', 'Wood-fired pizza', 'Garden setting'], address: 'Jl. Tirtodipuran No. 24A, Yogyakarta', opening_hours: '17:00 – 23:00' },
  { id: 'r3', slug: 'gudeg-yu-djum', name_en: 'Gudeg Yu Djum', name_id: 'Gudeg Yu Djum', cuisine: 'javanese', price_range: '$', regency: 'kota-yogyakarta', hero_image_url: 'https://images.unsplash.com/photo-1555396273-367ea4eb4db5?w=1200&q=80', gallery_image_urls: ['https://images.unsplash.com/photo-1567337710282-00832b415979?w=1200&q=80', 'https://images.unsplash.com/photo-1504674900247-0877df9cc836?w=1200&q=80'], descriptor_en: 'You cannot claim to have visited Jogja without eating gudeg — young jackfruit slow-cooked in coconut milk and palm sugar for hours. Yu Djum has been serving the definitive version since 1950, and locals will happily argue that no other stall comes close. Come hungry, come early.', descriptor_id: 'Belum sah datang ke Jogja kalau belum makan gudeg — nangka muda yang dimasak berjam-jam dengan santan dan gula aren. Yu Djum sudah menyajikan versi paling ikoniknya sejak 1950, dan orang lokal siap berdebat bahwa tidak ada gudeg lain yang menandinginya. Datanglah lapar, dan datanglah pagi-pagi.', highlights: ['Serving since 1950', 'Local institution', 'Ready to travel (takeaway)', 'Cash only'], address: 'Jl. Wijilan No. 167, Yogyakarta', opening_hours: '05:00 – 22:00' },
];

export const DUMMY_TRANSPORTATION = [
  { id: 't1', slug: 'airport-shuttle', name_en: 'Airport Shuttle Service', name_id: 'Layanan Shuttle Bandara', type: 'shuttle', price_idr: 75000, hero_image_url: 'https://images.unsplash.com/photo-1544620347-c4fd4a3d5957?w=1200&q=80', gallery_image_urls: ['https://images.unsplash.com/photo-1436491865332-7a61a109cc05?w=1200&q=80', 'https://images.unsplash.com/photo-1540962351504-03099e0a754b?w=1200&q=80'], descriptor_en: 'Yogyakarta International Airport (YIA) is about 45 kilometres from the city — further than most travellers expect. This shared shuttle runs on a fixed schedule to major hotels in central Jogja, saving you the negotiation and roughly half the cost of a private car. Book ahead, especially for late-night arrivals.', descriptor_id: 'Bandara Internasional Yogyakarta (YIA) berjarak sekitar 45 km dari kota — lebih jauh dari perkiraan banyak wisatawan. Shuttle bersama ini beroperasi terjadwal ke hotel-hotel utama di pusat kota, hemat waktu tawar-menawar dan sekitar setengah harga mobil pribadi. Pesan lebih awal, terutama untuk kedatangan malam.', highlights: ['Fixed schedule', 'Door-to-hotel drop-off', 'English-speaking driver', 'Advance booking recommended'], pickup_en: 'YIA Airport Arrival Hall, Kulon Progo', pickup_id: 'Terminal Kedatangan YIA, Kulon Progo' },
  { id: 't2', slug: 'car-rental-daily', name_en: 'Daily Car Rental with Driver', name_id: 'Sewa Mobil Harian dengan Sopir', type: 'rental', price_idr: 500000, hero_image_url: 'https://images.unsplash.com/photo-1449965408869-eaa3f722e40d?w=1200&q=80', gallery_image_urls: ['https://images.unsplash.com/photo-1494976388531-d1058494cdd8?w=1200&q=80', 'https://images.unsplash.com/photo-1533473359331-0135ef1b58bf?w=1200&q=80'], descriptor_en: 'For destinations like Borobudur, Prambanan, or the southern beaches, a private driver is honestly the smartest choice — cheaper than three separate day tours, and infinitely more flexible. Rate covers the vehicle, fuel, and a driver who knows the roads (and the shortcuts). Ten hours, up to seven passengers.', descriptor_id: 'Untuk tujuan seperti Borobudur, Prambanan, atau pantai selatan, mobil dengan sopir sebenarnya pilihan tercerdas — lebih murah dari tiga tur harian terpisah, dan jauh lebih fleksibel. Harga sudah termasuk kendaraan, bensin, dan sopir yang paham jalan (dan jalan tikus). 10 jam, sampai 7 penumpang.', highlights: ['10 hours included', 'Fuel & driver included', 'Up to 7 passengers', 'Custom itinerary'], pickup_en: 'Pick-up at your hotel, anywhere in Yogyakarta', pickup_id: 'Jemput di hotel, di mana saja di Yogyakarta' },
  { id: 't3', slug: 'motorbike-rental', name_en: 'Motorbike Rental', name_id: 'Sewa Motor', type: 'rental', price_idr: 80000, hero_image_url: 'https://images.unsplash.com/photo-1558981403-c5f9899a28bc?w=1200&q=80', gallery_image_urls: ['https://images.unsplash.com/photo-1509833903111-9cb142f644d0?w=1200&q=80', 'https://images.unsplash.com/photo-1568772585407-9361f9bf3a87?w=1200&q=80'], descriptor_en: 'A motorbike is the way most Jogja locals get around — cheap, quick, and perfect for weaving through the narrow lanes of the Kraton area or riding out to the southern beaches. Automatic scooters (Vario, Beat) are recommended for first-time riders. Bring an international driving permit and wear the helmet.', descriptor_id: 'Motor adalah cara orang Jogja bergerak sehari-hari — murah, cepat, dan sempurna untuk menembus lorong-lorong sempit sekitar Keraton atau berkendara ke pantai selatan. Skuter matic (Vario, Beat) direkomendasikan untuk pemula. Bawa SIM internasional dan selalu pakai helm.', highlights: ['Automatic scooter', 'Helmet included', 'Fuel not included', 'IDP required'], pickup_en: 'Rental office near Malioboro, or hotel delivery', pickup_id: 'Kantor sewa dekat Malioboro, atau antar ke hotel' },
];
